sonar.projectKey=cems_root
sonar.projectName=cems_root
sonar.projectVersion=1.0
sonar.sources=backend/src/main/java,frontend/src/main/java,shared/src/main/java
sonar.tests=backend/src/test/java,frontend/src/test/java
sonar.java.binaries=backend/target/classes,frontend/target/classes,shared/target/classes
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml
sonar.host.url=http://localhost:9000
sonar.coverage.exclusions=frontend/src/main/java/com/cems/frontend/controller/**, **/com/cems/shared/model/**, **/com/cems/frontend/services/AuthHandlingClient.java
sonar.exclusions=frontend/src/main/java/com/cems/frontend/controller/**