sonar.projectKey=cems_root
sonar.projectName=cems_root
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000

sonar.modules=backend,frontend,shared

# BACKEND MODULE
backend.sonar.sources=backend/src/main/java
backend.sonar.tests=backend/src/test/java
backend.sonar.java.binaries=backend/target/classes
backend.sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

# FRONTEND MODULE
frontend.sonar.sources=frontend/src/main/java
frontend.sonar.java.binaries=frontend/target/classes
frontend.sonar.coverage.jacoco.xmlReportPaths=frontend/target/site/jacoco/jacoco.xml

# SHARED MODULE
shared.sonar.sources=shared/src/main/java
shared.sonar.tests=shared/src/test/java
shared.sonar.java.binaries=shared/target/classes
shared.sonar.coverage.jacoco.xmlReportPaths=shared/target/site/jacoco/jacoco.xml

# EXCLUSIONS
frontend.sonar.exclusions=**/com/cems/frontend/controller/**
frontend.sonar.coverage.exclusions=**/com/cems/frontend/controller/**,**/com/cems/frontend/services/AuthHandlingClient.java

shared.sonar.exclusions=**/com/cems/shared/model/**
shared.sonar.coverage.exclusions=**/com/cems/shared/model/**
